DROP SCHEMA IF EXISTS gpManagementSystem;

CREATE SCHEMA gpManagementSystem;

USE gpManagementSystem;

CREATE TABLE doctors (
  `DID` INT NOT NULL AUTO_INCREMENT,
  `F_Name` VARCHAR(45) NULL,
  `L_Name` VARCHAR(45) NULL,
  `Username` VARCHAR(45) NULL,
  `Password` VARCHAR(45) NULL,
  PRIMARY KEY (`DID`),
  UNIQUE INDEX `DID_UNIQUE` (`DID` ASC) VISIBLE);

CREATE TABLE patients (
  `PID` INT NOT NULL AUTO_INCREMENT,
  `F_Name` VARCHAR(45) NOT NULL,
  `L_Name` VARCHAR(45) NOT NULL,
  `Username` VARCHAR(45) NOT NULL,
  `Password` VARCHAR(45) NOT NULL,
  `P_Number` VARCHAR(11) NOT NULL,
  `Address` VARCHAR(200) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`PID`),
  UNIQUE INDEX `PID_UNIQUE` (`PID` ASC) VISIBLE);
  
CREATE TABLE access_log (
  `LID` INT NOT NULL AUTO_INCREMENT,
  `time` TIMESTAMP NOT NULL,
  `DID` INT NOT NULL,
  `Action` VARCHAR(200) NOT NULL,	
  PRIMARY KEY (`LID`),
  FOREIGN KEY (`DID`) REFERENCES doctors (`DID`)
);

CREATE TABLE bookings (
    `BID` INT NOT NULL AUTO_INCREMENT,
    `DID` INT NOT NULL,
    `PID` INT NOT NULL,
    `Date` DATE NOT NULL,
    PRIMARY KEY (`BID`),
    FOREIGN KEY (`DID`) REFERENCES doctors (`DID`),
    FOREIGN KEY (`PID`) REFERENCES patients (`PID`));

CREATE TABLE past_visits(
  `VID` INT NOT NULL AUTO_INCREMENT,
  `Date` DATE NOT NULL,
  `DID` INT NOT NULL,
  `PID` INT NOT NULL,
  `Comments` VARCHAR(256),
  `Prescriptions` VARCHAR(256),
  PRIMARY KEY (`VID`),
  FOREIGN KEY (`PID`) REFERENCES patients (`PID`),
  FOREIGN KEY (`DID`) REFERENCES doctors (`DID`)
);